# Generated by Django 5.0.4 on 2024-05-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_benefit_type_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='employee',
        ),
    ]
