# Generated by Django 4.2.16 on 2024-10-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_remove_benefit_employee_remove_deduction_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolldetails',
            name='payroll',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='PayrollDetails',
        ),
    ]
