# Generated by Django 5.2.7 on 2025-10-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='percentage_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If percentage-based, enter a value like 10 for 10%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
